--SELECT fun_conse();

CREATE OR REPLACE FUNCTION fun_conse() RETURNS INTEGER AS

$$ 
	DECLARE ULTIMO_ID INTEGER;

	BEGIN
		SELECT MAX (a.val_consec) INTO ULTIMO_ID  FROM tab_kardex a;

		IF ULTIMO_ID IS NULL THEN
			ULTIMO_ID=1;

			RAISE NOTICE 'funca %', ULTIMO_ID;

			RETURN ULTIMO_ID;
		END IF;
		ULTIMO_ID=ULTIMO_ID+1;
		RETURN ULTIMO_ID;

	END;

$$
LANGUAGE PLPGSQL;
